package Capa_Presentacion;

import Capa_Negocio.DataEstudiante;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

public class Formulario_Estudiante extends javax.swing.JFrame {

    /**
     * Creates new form Formulario_Inventario
     */
    public Formulario_Estudiante() {
        initComponents();
        ListarEstudiante();
        jBGrabar.setEnabled(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public void ListarEstudiante() {
        DefaultTableModel tablaEst = new DefaultTableModel();
        DataEstudiante objest = new DataEstudiante();
        ArrayList<DataEstudiante> listaEst = new ArrayList();
        listaEst = objest.ListaEstudiante();
        tablaEst.addColumn("Codigo");
        tablaEst.addColumn("Nombre");
        tablaEst.addColumn("Cantidad");
        tablaEst.addColumn("Estado");
        tablaEst.setRowCount(listaEst.size());
        int i = 0;
        for(DataEstudiante x : listaEst){
            tablaEst.setValueAt(x.getEs_identificacion(), i, 0);
            tablaEst.setValueAt(x.getEs_nombre_completo(), i, 1);
            tablaEst.setValueAt(x.getEs_carrera(), i, 2);
            tablaEst.setValueAt(x.getEs_Email(), i, 3);
            i++;
        }
        this.jTEstudiantes.setModel(tablaEst);
    }

    public void LimpiarCajasTexto(){
        this.TFId.setText("");
        this.TFNombreCompleto.setText("");
        this.TFEmail.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TFId = new javax.swing.JTextField();
        TFNombreCompleto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTEstudiantes = new javax.swing.JTable();
        jBNuevo = new javax.swing.JButton();
        jBGrabar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        CBCarrera = new javax.swing.JComboBox<>();
        TFEmail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Identidicacion");

        jLabel2.setText("Nombre Completo");

        jLabel3.setText("Carrera");

        jLabel4.setText("Email");

        TFId.setText("");

        TFNombreCompleto.setText("");

        TFEmail.setText("");

        CBCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ing Industrial",
                "Ciencias de la computacion", "Ing Ambiental", "Ing Electronica" }));

        jTEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(jTEstudiantes);

        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBGrabar.setText("Grabar");
        jBGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGrabarActionPerformed(evt);
            }
        });

        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jTEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTEstudiantesMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jBNuevo)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jBGrabar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jBModificar)
                                                .addGap(18, 18, 18)
                                                .addComponent(jBEliminar)
                                                .addGap(18, 18, 18)
                                                .addComponent(jBSalir))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(TFId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(1, 1, 1)
                                                                .addComponent(TFNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(CBCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(TFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(40, 40, 40)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(43, 43, 43)
                                                                .addComponent(jLabel2))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel1)
                                                                        .addComponent(TFId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(TFNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(CBCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel3))
                                                .addGap(21, 21, 21)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(TFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jBNuevo)
                                        .addComponent(jBGrabar)
                                        .addComponent(jBModificar)
                                        .addComponent(jBEliminar)
                                        .addComponent(jBSalir))
                                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {
        LimpiarCajasTexto();
        // opcional para mas delante: q ponga el codigo solo
        jBGrabar.setEnabled(true);
    }

    private void jBGrabarActionPerformed(java.awt.event.ActionEvent evt) {
        String identificacion = TFId.getText().trim();
        String nombreCompleto = TFNombreCompleto.getText().trim();
        String email = TFEmail.getText().trim();

        if (identificacion.isEmpty() || nombreCompleto.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe completar todos los campos",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int id = Integer.parseInt(identificacion);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "La identificacion debe ser un valor numerico entero",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        DataEstudiante objest = new DataEstudiante();
        objest.setEs_identificacion(Integer.parseInt(this.TFId.getText()));
        objest.setEs_nombre_completo(this.TFNombreCompleto.getText());
        objest.setEs_carrera(this.CBCarrera.getSelectedItem().toString());
        objest.setEs_Email(this.TFEmail.getText());
        objest.GrabarEstudiante();
        JOptionPane.showMessageDialog(null, "Articulo grabado con exito");
        ListarEstudiante();
    }

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {
        String id = TFId.getText().trim();
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese una identificacion valida");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTEstudiantes.getModel();
        boolean existe = false;
        for (int i = 0; i < model.getRowCount(); i++) {
            String podibleId = model.getValueAt(i, 0).toString();
            if (podibleId.equals(id)) {
                existe = true;
                break;
            }
        }

        if (!existe) {
            JOptionPane.showMessageDialog(this, "El estudiante no existe");
            return;
        }

        DataEstudiante objest = new DataEstudiante();
        objest.setEs_identificacion(Integer.parseInt(id));
        objest.setEs_nombre_completo(this.TFNombreCompleto.getText());
        objest.setEs_carrera(this.CBCarrera.getSelectedItem().toString());
        objest.setEs_Email(this.TFEmail.getText());
        objest.EditarEstudiante();
        JOptionPane.showMessageDialog(null, "Estudiante modificado");
        ListarEstudiante();
    }

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {
        String id = TFId.getText().trim();
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese una identificacion valida");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTEstudiantes.getModel();
        boolean existe = false;
        for (int i = 0; i < model.getRowCount(); i++) {
            String podibleId = model.getValueAt(i, 0).toString();
            if (podibleId.equals(id)) {
                existe = true;
                break;
            }
        }

        if (!existe) {
            JOptionPane.showMessageDialog(this, "El estudiante no existe");
            return;
        }

        int Res = JOptionPane.showConfirmDialog(null,
                "Estas seguro de eliminar el estudiante: " + id + "?",
                "Confirmar Eliminación",
                JOptionPane.YES_NO_OPTION);
        if (Res == JOptionPane.YES_OPTION) {
            DataEstudiante objinv = new DataEstudiante();
            objinv.setEs_identificacion(Integer.parseInt(id));
            objinv.EliminarEstudiante();
            JOptionPane.showMessageDialog(null, "Estudiante Eliminado");
            ListarEstudiante();
        }
    }

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {
        int r = JOptionPane.showConfirmDialog(null, "Esta seguro?");
        if (r == 0){
            System.exit(0);
        }
    }

    private void jTEstudiantesMousePressed(java.awt.event.MouseEvent evt) {
        int rec = this.jTEstudiantes.getSelectedRow();
        this.TFId.setText(jTEstudiantes.getValueAt(rec, 0).toString());
        this.TFNombreCompleto.setText(jTEstudiantes.getValueAt(rec, 1).toString());
        this.CBCarrera.setSelectedItem(jTEstudiantes.getValueAt(rec, 2).toString());
        this.TFEmail.setText(jTEstudiantes.getValueAt(rec, 3).toString());
    }

    // Variables declaration - do not modify
    private javax.swing.JComboBox<String> CBCarrera;
    private javax.swing.JTextField TFEmail;
    private javax.swing.JTextField TFId;
    private javax.swing.JTextField TFNombreCompleto;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGrabar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTEstudiantes;
    // End of variables declaration
}
