package Capa_Presentacion;

import javax.swing.*;
import java.awt.event.ActionEvent;

public class Formulario_Main extends javax.swing.JFrame {
    /**
     * Creates new form Formulario_Main
     */
    public Formulario_Main() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Main");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMInventario = new javax.swing.JMenu();
        jMiInventario = new javax.swing.JMenuItem();
        jMEstudiantes = new javax.swing.JMenu();
        jMiEstudiantes = new javax.swing.JMenuItem();
        jMPrestamos = new javax.swing.JMenu();
        jMiPrestamos = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();
        jMiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMInventario.setText("Inventario");

        jMiInventario.setText("Inventario");
        jMiInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiInventarioActionPerformed(evt);
            }
        });
        jMInventario.add(jMiInventario);

        jMenuBar1.add(jMInventario);

        jMEstudiantes.setText("Estudiantes");

        jMiEstudiantes.setText("Estudiantes");
        jMiEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiEstudiantesActionPerformed(evt);
            }
        });
        jMEstudiantes.add(jMiEstudiantes);

        jMenuBar1.add(jMEstudiantes);

        jMPrestamos.setText("Prestamos");

        jMiPrestamos.setText("Prestamos");
        jMiPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiPrestamosActionPerformed(evt);
            }
        });
        jMPrestamos.add(jMiPrestamos);

        jMenuBar1.add(jMPrestamos);

        jMSalir.setText("Salir");

        jMiSalir.setText("Salir");
        jMiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMiSalirActionPerformed(evt);
            }
        });
        jMSalir.add(jMiSalir);

        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 343, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 227, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void jMiInventarioActionPerformed(java.awt.event.ActionEvent evt) {
        Formulario_Inventario fi = new Formulario_Inventario();
        fi.setVisible(true);
    }

    private void jMiEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {
        Formulario_Estudiante fe = new Formulario_Estudiante();
        fe.setVisible(true);
    }

    private void jMiPrestamosActionPerformed(java.awt.event.ActionEvent evt) {
        Formulario_Prestamo fp = new Formulario_Prestamo();
        fp.setVisible(true);
    }

    private void jMiSalirActionPerformed(java.awt.event.ActionEvent evt) {
        int r = JOptionPane.showConfirmDialog(null, "Esta seguro?");
        if (r == 0){
            System.exit(0);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Formulario_Main main = new Formulario_Main();
        main.setVisible(true);
    }

    // Variables declaration - do not modify
    private javax.swing.JMenu jMEstudiantes;
    private javax.swing.JMenu jMInventario;
    private javax.swing.JMenu jMPrestamos;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMiEstudiantes;
    private javax.swing.JMenuItem jMiInventario;
    private javax.swing.JMenuItem jMiPrestamos;
    private javax.swing.JMenuItem jMiSalir;
    // End of variables declaration
}
